### ISSUE TITLE
Does Premailer.Net support XHTML Strict?

### ISSUE THREAD

**Issue by driekus77** [milkshakesoftware/PreMailer.Net#101]
Dear all,

Two quick questions: 
- Does Premailer.Net support CSS Inlining XHTML Strict?
- Why is the DocType being removed by the Premailer.Net?

The reason I'm asking is we want to use your tool in our e-mail services but are having difficulties getting the layout straigth. I've already checked the XHTML Strict html file with both HTML and CSS validators from W3C and there are fine.

Hope you can help me.

Kind regards,

Henry Roeland

[Premailer drip test.zip](https://github.com/milkshakesoftware/PreMailer.Net/files/221630/Premailer.drip.test.zip)

**Comment by martinnormark** [comment]
Hey @driekus77 

For no good reason, the DOCTYPE is not maintained, so that becomes a showstopper for your XHTML Strict inlining.

Other issues with this problem has also been reported #38 and #97 

PreMailer should touch as little of the HTML as possible.

**Comment by martinnormark** [comment]
Cutting a new release now, will be on Nu Get shortly.

**Comment by driekus77** [comment]
Hi @martinnormark,

Thanks for your very quick respondse and actions!

I've tested it and the DocType is now preserved.

Thanks again and Kind regards,

Henry Roeland
