### ISSUE TITLE
Need signed dll

### ISSUE THREAD

**Issue by prashantbhide** [milkshakesoftware/PreMailer.Net#111]
Hi,

We need a signed version of the dll. Is it possible to please upload a signed binary?

Thanks,
Prashant.

**Comment by rheaney** [comment]
+1, would be nice to have, as we are basically blocked otherwise

**Comment by superlogical** [comment]
Just clone the code and build it yourself if you need it to be signed.

**Comment by martinnormark** [comment]
New version on nuget has strong name signing.
