### ISSUE TITLE
PreMailer.NET Issue with bullets(•)

### ISSUE THREAD

**Issue by raiswapniln** [milkshakesoftware/PreMailer.Net#116]
I have MS-Word file which is converted to .html and it contains (•).
PreMailer.NET converting • into some wrong characters.

**Comment by martinnormark** [comment]
Likely related to #114

**Comment by raiswapniln** [comment]
Thanks Martin for your prompt reply.
I have resolved this issue by using HTMLAgilityPack. The PreMailer.NET is working great.
