### ISSUE TITLE
Moves `<head>` contents to body

### ISSUE THREAD

**Issue by haf** [milkshakesoftware/PreMailer.Net#124]
## Description of issue
This may be the expected behaviour.

### Input:
<img width="399" alt="screen shot 2016-09-07 at 22 42 10" src="https://cloud.githubusercontent.com/assets/193115/18327788/5c74e7c0-754c-11e6-8dc7-3f15ae85db7a.png">

### Output:

<img width="685" alt="screen shot 2016-09-07 at 22 41 22" src="https://cloud.githubusercontent.com/assets/193115/18327768/457b3538-754c-11e6-8065-29dc12729c87.png">
<img width="453" alt="screen shot 2016-09-07 at 23 02 51" src="https://cloud.githubusercontent.com/assets/193115/18328468/3ef7a914-754f-11e6-9df5-f0539a9f49c8.png">

### Expected behaviour:

For it to keep head contents in the head.

### Usage:

```fsharp
      use pre = new PreMailer(contents, liquidData.baseUri)
      let res =
        pre.MoveCssInline(
          removeComments = true,
          removeStyleElements = true,
          ignoreElements = ".keep"
        )

      for x in res.Warnings do
        Message.eventWarn x |> logger.logSimple // log with Logary

      HtmlString res.Html
```

### Notes

 - Similar issue without `removeComments`, `removeStyleElements`.
 - There are no warnings in the output.

**Comment by codykonior** [comment]
I think this is expected behaviour. The reason being that email readers will strip contents out of head and cause a lot of failures, which is why PreMailer.Net is moving them into the body. This is the same way that other inliners do it also.

With that said I'm not against anyone adding an option to turn it off :-)

**Comment by haf** [comment]
Makes sense. :) It works fine with the e-mail clients, too. So I'm closing this issue.
