### ISSUE TITLE
MissingMethodException (AngleSharp 0.9.9)

### ISSUE THREAD

**Issue by JasonLooney** [milkshakesoftware/PreMailer.Net#128]
I just updated to the latest nuget packages for PreMailer.Net (1.5.4) and AngleSharp (0.9.9) and I now receive the following exception when calling MoveCssInline:

**Type:** 
System.MissingMethodException

**Message:** 
Method not found: 'Void AngleSharp.Dom.IElement.RemoveAttribute(System.String)'. 

**Stack Trace:** 
at PreMailer.Net.StyleClassApplier.ApplyStyles(IElement domElement, StyleClass clazz) 
at PreMailer.Net.StyleClassApplier.ApplyAllStyles(Dictionary`2 elementDictionary) 
at PreMailer.Net.PreMailer.MoveCssInline(Boolean removeStyleElements, String ignoreElements, String css, Boolean stripIdAndClassAttributes, Boolean removeComments) 
at PreMailer.Net.PreMailer.MoveCssInline(String html, Boolean removeStyleElements, String ignoreElements, String css, Boolean stripIdAndClassAttributes, Boolean removeComments)

**Comment by JasonLooney** [comment]
Sorry for posting this. This appears to be an issue specific to my project, not PreMailer. Closing.

**Comment by martinnormark** [comment]
No worries.

**Comment by har07** [comment]
@JasonLooney  Somebody seems to be experiencing the same problem in [this StackOverflow post](http://stackoverflow.com/questions/40281157/premailer-method-not-found-anglesharp-dom-ielement-removeattribute). Could you share what was the solution for your case? Maybe it applies to his case as well..

**Comment by JasonLooney** [comment]
Looking at my commit log, it looks like I downgraded AngleSharp to 0.9.5. Everything works fine for me now. Unfortunately I can't remember all of the details behind this change. I was trying to move to .NET Standard that day and ended up throwing in the towel and reverting back to PCLs and .NET 4.6.1.

**Comment by shyamal890** [comment]
Having the same issue after the upgrade wonder caused this. @martinnormark any ideas?

**Comment by martinnormark** [comment]
Yes, this issue is the same as #130 - I hope to cut a new release tonight that fixes it.
