### ISSUE TITLE
System.Net.WebException  processing html with a localhost css address

### ISSUE THREAD

**Issue by pbrianmackey** [milkshakesoftware/PreMailer.Net#134]
Error:  The request was aborted: The operation has timed out.

Sample:  `<link href=\"http://localhost/path/path2/styles/normalize.min.css\" rel=\"stylesheet\"> `

I can navigate to the path successfully using a web browser.  If I remove this stylesheet from the html source then the error goes away.  

Is there a restriction in PreMailer to not be able to use localhost?

**Comment by pbrianmackey** [comment]
I used a console app to test this with.  I switched to a website app and the issue resolved itself.  I believe there are restrictions around what a console app can access.

**Comment by martinnormark** [comment]
👍 Thanks for the update. There shouldn't me any limitation in PreMailer. As long as the network can reach the URL, it should work as expected.
