### ISSUE TITLE
Installation .Net Core

### ISSUE THREAD

**Issue by Cor4xX** [milkshakesoftware/PreMailer.Net#137]
Hi,

I'm working on .net core (ASP c#) but i cannot figure out how to make premailer works with it. 

I try to reference "PreMailer.Net": "1.5.5" and "PreMailer.Net": "1.6.0-*"

Here is my project.json

`"dependencies": {
    "Microsoft.AspNetCore.Identity": "1.1.0",
    "Microsoft.AspNetCore.Mvc.Core": "1.1.0",
    "Microsoft.NETCore.App": "1.1.0",
    "PreMailer.Net": "1.6.0-*"
  },
  "frameworks": {
    "netcoreapp1.1": {
      "imports": "dnxcore50"
    }
  },
  "runtimes": {
    "win10-x64": {},
    "debian.8-x64": {}
  }`

**Comment by sebok** [comment]
Hi @Cor4xX, .NET Core is not yet supported by PreMailer.Net. I've created pull request #122 to add this support.
Meanwhile, you can download Nuget packages from [this release](https://github.com/sebok/PreMailer.Net/releases/tag/v1.5.6).

**Comment by martinnormark** [comment]
Support added in #141
