### ISSUE TITLE
Duplicated style properties added with different values

### ISSUE THREAD

**Issue by nbajko** [milkshakesoftware/PreMailer.Net#138]
Hi, 

In some particular cases, we found that MoveCssInline is adding duplicated style properties with different values to a node:

![image](https://cloud.githubusercontent.com/assets/10599190/22901407/605396fc-f210-11e6-8f87-9060734f6170.png)

These are the styles applied to that anchor tag that has the duplicated `font-family` and `font-weight` properties:

```
a {
  color: #0a0a0a;
  font-family: Helvetica, Arial, sans-serif;
  font-weight: normal;
  padding: 0;
  margin: 0;
  Margin: 0;
  text-align: left;
  line-height: 1.3; 
}
table a {
    color: #0066cc;
    font-weight: 600;
    font-family: 'Segoe UI', Verdana, Arial, sans-serif;
    text-decoration: underline; 
}
```

Debugging we found an issue with the single quotes in the `table a` `font-family` style. If we replace the single quotes by double quotes, the inline styles are correct: 

![image](https://cloud.githubusercontent.com/assets/10599190/22901683/4148b34a-f211-11e6-8bdd-579eab1ec2ac.png)

**Comment by nbajko** [comment]
Submitted PR #139 to fix the issue

**Comment by martinnormark** [comment]
Sorry for the delay @nbajko - merged now, will push a new pre-release version shortly.
