### ISSUE TITLE
Modifier '!important' is duplicated

### ISSUE THREAD

**Issue by Loadmaster** [milkshakesoftware/PreMailer.Net#140]
_Using v 1.5.5_

I'm getting a duplicate `!important` style modifier on a `color` style definition:
` ... color: #ffffff!important !important; ...`

Some browsers (Firefox) do not seem to like this duplication, causing the entire `color` definition to be ignored.

I have a quick work-around for now, using a simple string replacement:
`    string htmlBody = inLineResult.Html.Replace("!important !important", " !important");`

The downside to this it that it can be a relatively expensive operation on email texts larger than 20K or so.

**Comment by BickelLukas** [comment]
#151 same problem
I created a Pull request solving the problem

**Comment by martinnormark** [comment]
Closed by #151
