### ISSUE TITLE
Html Render Title tag (1.5.3 vs 1.5.5)

### ISSUE THREAD

**Issue by vinhhrv** [milkshakesoftware/PreMailer.Net#142]
PreMailler version 1.5.5 self close tag title when render html with doctype is xhtml

### My Test Case

`using (var pm = new PreMailer.Net.PreMailer(
                "<!DOCTYPE html PUBLIC \"XHTML\"><html><head><title></title></head><body>abc</body></html>"))`
            `{`
                `var content = pm.MoveCssInline().Html;`
`Assert.Equal(content, "<!DOCTYPE html PUBLIC \"XHTML\"><html><head><title></title></head><body>abc</body></html>");`
`}`

1.5.3 oke, but fail when i use 1.5.5

Browser display nothing when title tag close

**Comment by reinaldocoelho** [comment]
This occours to me too.
Ending all tags with <tag/> cause some problems on HTML bodys.
Some intention to solve this?

**Comment by martinnormark** [comment]
Should work now.
