### ISSUE TITLE
Embedding images

### ISSUE THREAD

**Issue by ryoshi1986** [milkshakesoftware/PreMailer.Net#143]
Hi,

i am trying to embed an image in my mail like so: 

```
<img src="data:image/png;base64,iVBORw0KGgoAAA
ANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4
//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU
5ErkJggg==" alt="Red dot" />
```

In another issue here it says this is the right way. But the 
image won´t render.

Can you help me fix this issue?

Greetings

**Comment by ryoshi1986** [comment]
The image won´t show up in:
gmail browser, thunderbird, win10 mail app, gmail app

**Comment by martinnormark** [comment]
Was the code from your source, or from the end result after running PreMailer?

**Comment by ryoshi1986** [comment]
This code is from my source view, before PreMailer.

**Comment by martinnormark** [comment]
Ok, I don't know why it doesn't display in email clients. One [issue could be compatibility](https://www.campaignmonitor.com/blog/email-marketing/2013/02/embedded-images-in-html-email/). Closing this issue, as it doesn't relate to PreMailer.
