### ISSUE TITLE
Feature request: disable automatic wrapping of content into HTML tags

### ISSUE THREAD

**Issue by grokky1** [milkshakesoftware/PreMailer.Net#144]
When passing in any string, e.g. `Hello world`, what I get is `<html>...etc etc...<body>Hello world</body></html>` Not sure if this is something that I'm doing wrong or intended behavior?

Consider that emails are often composed as HTML "fragments" rather than full HTML documents. So this is not desirable. For example, I have a subject template, which obviously should not be converted to HTML.

Would be nice to have an argument `bool WrapAsHtml = true` or something like that, that I can disable. This would not be a breaking change.

**Comment by martinnormark** [comment]
Returning an HTML document is by design, as PM uses a third party renderer. 

Getting it out of HTML document can be handled at application level.
