### ISSUE TITLE
Feature request: remove whitespace

### ISSUE THREAD

**Issue by grokky1** [milkshakesoftware/PreMailer.Net#146]
It is desirable for emails to be as small as possible. However the templates we use to create them have lots of whitespace - obviously because of residue of server-side markup and comments, and whitespace to make it easier to read the template, etc.

Would be useful to have a new argument `bool removeWhitespace = false` which would strip all whitespace. So the output would be one long line of text.

Would not be a breaking change.

**Comment by alekdavis** [comment]
Do you mean removing line breaks? Generally, whitespace includes space characters, tabs, new lines, etc. You definitely do not want to remove all white space characters, right?

**Comment by grokky1** [comment]
Whitespace between tags is useless and should be removed. Whitespace within tags should not be removed.

**Comment by alekdavis** [comment]
Not necessarily, e.g. <b>hello</b> <i>world</i> is not the same as <b>hello</b><i>world</i>.

**Comment by grokky1** [comment]
Your example is presumably within a tag? If so then it should not be minified.

Here's an example:

Should not be minified:
````
<span>Hello  

      world</span>
````


Should be minified:
````
<span>Hello world</span>         <b>!</b>
````

**Comment by alekdavis** [comment]
&lt;b&gt;Hello&lt;/b&gt; &lt;i&gt;world&lt;/i&gt; (with a space character between &lt;/b&gt; and &lt;i&gt;) is not the same as &lt;b&gt;Hello&lt;/b&gt;&lt;i&gt;world&lt;/i&gt; (without the space character).

**Comment by grokky1** [comment]
I don't think I understand your point? Whitespace between tags is useless and should be removed. Are you saying there are cases where this is not true?

I suppose for verbatim text, but who writes markup like that?

Besides this would be a configurable option.
