### ISSUE TITLE
Moving from 1.5.5 to 2.0.0 causes problems to my project

### ISSUE THREAD

**Issue by bragma** [milkshakesoftware/PreMailer.Net#161]
Hi,
I have an asp net core 1.1 project using razor as template engine and premailer 1.55. I've tried to update to 2.0.0 and while everything compiles, I have an exception due to missing Microsoft.CSharp.dll in "refs" folder. I noticed that the refs folder was not present before the update to 2.0.0 and tracked the problem to this single package update. I am not a super expert and I only have a minor understanding of what's the "refs" folder for (I am compiling with PreserveCompilationContext set to true). Anyone can help? Thanks!

**Comment by martinnormark** [comment]
Try v2.1.0 - just hit nuget.
