### ISSUE TITLE
Best way to process an AngleSharp.IHtmlDocument with PreMailer

### ISSUE THREAD

**Issue by axunonb** [milkshakesoftware/PreMailer.Net#164]
I'm putting together an ```AngleSharp.IHtmlDocument``` from various parts, until it is ready to be sent as an email. But before sending the mail, ```PreMailer``` should do some in-line magic. There are no overloads for ctor/methods taking an```IHtmlDocument``` in PreMailer. So I'm considering the following solution which seems to do the job, avoiding unnecessary conversions from/to strings. Would you recommend a different way?
```csharp
class Program
{
    private static string realHtml = @"
<html>
<head>
<style>
h1 {color:red;}
p {color:blue;}
</style>
</head>
<body>
<h1>A heading</h1>
<p>A paragraph.</p>
</body>
</html> 
";
    private static string minimalHtml = @"<html></html>";

    static void Main(string[] args)
    {
        var parser = new HtmlParser();
        var document = parser.Parse(realHtml);
        document = PostProcessHtml(document);
        Console.WriteLine(document.DocumentElement.OuterHtml);
        document.Dispose();
    }

    // This is similar to what I would be going to implement:
    static IHtmlDocument PostProcessHtml(IHtmlDocument htmlDoc)
    {
        IHtmlDocument toReturn;
        using (var pm = new PreMailer.Net.PreMailer(minimalHtml, null))
        {
            pm.Document.Head.Remove();
            pm.Document.Body.Remove();

            pm.Document.DocumentElement.Append(htmlDoc.Head);
            pm.Document.DocumentElement.Append(htmlDoc.Body);

            var dummy = pm.MoveCssInline(true);
            toReturn = (IHtmlDocument) pm.Document.Clone(true);
            htmlDoc.Dispose();
        }
        return toReturn;
    }
}
```

**Comment by leniency** [comment]
#169 added an additional constructor for these cases. Looks like it got accepted, but hasn't been published quite yet.

**Comment by axunonb** [comment]
> 
> 
> #169 added an additional constructor for these cases. Looks like it got accepted, but hasn't been published quite yet.

This is definitely better than solution I came about. Thanks for your PR!

**Comment by martinnormark** [comment]
I will cut a new release over the weekend, so the constructor overload that takes an HtmlDocument will be available soon.

**Comment by axunonb** [comment]
> 
> 
> I will cut a new release over the weekend, so the constructor overload that takes an HtmlDocument will be available soon.

Would be really great if you could push the release to NuGet ;-)

**Comment by martinnormark** [comment]
Sorry for the delay, I need to review and merge #168 then I'll push it.
