### ISSUE TITLE
Could not load type AngleSharp.Parser.Html.HtmlParser

### ISSUE THREAD

**Issue by possumdelight** [milkshakesoftware/PreMailer.Net#174]
Calling .MoveCSSInline results in:

Could not load type 'AngleSharp.Parser.Html.HtmlParser' from assembly 'AngleSharp, Version=0.12.1.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea'.

I'm running .Net Framework 4.8, Premailer 2.0.1, and AngleSharp 0.12.1.  I recently updated from previous versions of all of the above.  I have tried downgrading and an unable to find a combination that works.

Any suggestions are appreciated.

Kind Regards,

Charles

**Comment by h1bay1** [comment]
We've also got the same problem here. We use multiple Nuget packages which both have a dependency on Anglesharp and PreMailer only supports an older version. 

Looks like the latest Anglesharp is .Net 46 up so premailer will need to be updated to .Net 46 to be compatible with that version.

**Comment by martinnormark** [comment]
AngleSharp is now at `v0.12.1` as per #175 - hitting nuget in a ⚡️
