### ISSUE TITLE
Inliner strips out vml from html tag 

### ISSUE THREAD

**Issue by bodixxx** [milkshakesoftware/PreMailer.Net#308]
If anyone can help me with this issue, i got some vml code that is stripped from html tag:

html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office"

after PreMailer i got:
html lang="en" xmlns="http://www.w3.org/1999/xhtml

the xmlsn:v is getting stripped out because of the ":" 

thank you

**Comment by martinnormark** [comment]
@bodixxx This may have been fixed since updating to latest version of AngleSharp. I added a test to verify in 6dc98b6fad1cc5af55235c8a354e7cfb5d5da5cb.

Change not released yet.
