### ISSUE TITLE
Browser-specific selector modifiers throw exception

### ISSUE THREAD

**Issue by albertbori** [milkshakesoftware/PreMailer.Net#37]
Some examples:

button::-moz-focus-inner,
input::-moz-focus-inner {
  padding: 0;
  border: 0;
}

.form-control:-moz-placeholder {
  color: #999999;
}

Error message:
Unexpected character found at position 15: \".. m-control::>>-<<moz-placeholder\"

Note: Although these are primarily form-related and therefore inconsequential to emails, it should not throw an exception while trying to parse these.

**Comment by hsandhar** [comment]
+1

**Comment by hsandhar** [comment]
I think its similar to Issue #37 (closed). Take a look at that one

**Comment by Benexx** [comment]
Version 1.3.1 still generates errors. For example:
PreMailer.cs:186
var elementsForSelector = _document["button::-moz-focus-inner"]

**Comment by hazzik** [comment]
Same here

**Comment by czapeek** [comment]
+1 on version 1.4.1 with button::-moz-focus-inner

**Comment by Almeonamy** [comment]
+1

**Comment by louislewis2** [comment]
Having the same error here. Is there any work around currently?

**Comment by smkanadl** [comment]
This is an issue related to CSQuery which should be fixed with a new release using AngleSharp. See this issue #79. A temporary workaround may be `var css = Regex.Replace(css, @"::-[a-z\-]+", "");`.

**Comment by louislewis2** [comment]
Thanks for the quick reply. I will have to change some code around and keep the css file local for that, I was hoping to make use of the download feature. Any ideas as to when a new cut will be out?

**Comment by smkanadl** [comment]
No. I think @martinnormark is the only one who can answer this question.

**Comment by louislewis2** [comment]
Is anyone using this with mdl from https://code.getmdl.io/1.1.1/material.indigo-pink.min.css?
Even after applying the suggested workaround I keep on getting other exceptions thrown. First one was ::- then just :: and now Unknown pseudo-class :"root". If this is a valid CSS or jQuery selector, please let us know.
