### ISSUE TITLE
Ambiguity with class name and root namespace

### ISSUE THREAD

**Issue by AaronLS** [milkshakesoftware/PreMailer.Net#43]
Is it just me or does anyone else have issues because the class PreMailer is also a root namespace?  Ctrl+. to auto resolve namespace does not work.  

Even when I have `using PreMailer.Net;` I still have to fully qualify the namespace as: `PreMailer.Net.PreMailer.MoveCssInline(htmlSource);` 

instead of `PreMailer.MoveCssInline(htmlSource);`

**Comment by denisz1** [comment]
I agree. Current naming conflicts with code inspection tools and code formatting suites, etc.

Could be `PremailerNet` instead of `Premailer.Net`:

    @using PremailerNet;

**Comment by zaha** [comment]
Any news on this?
Just started to use the library today and this is really a bad user experience. The suggestion from @denisz1 would be a good solution IMHO.
