### ISSUE TITLE
Pass the content of a CSS file via PremailerNet API

### ISSUE THREAD

**Issue by hidegh** [milkshakesoftware/PreMailer.Net#45]
If there would be a possibility to **pass the content of a CSS file via PremailerNet API**, you would:
-get rid of relative/absolute url links
-and we would get a possibility to use a single CSS to style every mail output...

**Comment by denisz1** [comment]
I agree with the need for this feature, and the OP's code is a good start. Should be added to the library. And remember it's optional, so you don't need to use it if you don't want to. Could be added as an overload.

**Comment by martinnormark** [comment]
API to pass a stylesheet as a string to PreMailer is invoked using the new `css` parameter:

`PreMailer.MoveCssInline(input, false, css: ".test { background-color:#f1f1f1; }")`

**Comment by denisz1** [comment]
@martinnormark Works awesome
