### ISSUE TITLE
 Add support for strong name signing (.snk)

### ISSUE THREAD

**Issue by Krashlog** [milkshakesoftware/PreMailer.Net#49]
I need to use PreMailer within a strongly-named assembly, simple as that. 

FYI, CsQuery is already has a strong name key.

**Comment by XmlmXmlmX** [comment]
Need this!

**Comment by bs93** [comment]
+1

**Comment by arisliang** [comment]
+1 for this!

**Comment by druczak** [comment]
+1

**Comment by martinnormark** [comment]
Hitting nuget soon: https://github.com/milkshakesoftware/PreMailer.Net/pull/159/commits/3579a0d0249791ddd2ea4129efacb7394d456580 - please, could someone test and let me know if it doesn't behave?
