### ISSUE TITLE
Is it possible to strip "class" and "id" attributes?

### ISSUE THREAD

**Issue by denisz1** [milkshakesoftware/PreMailer.Net#55]
There is an option for removing style blocks after processing. What about `class` and `id` attributes?

It is much easier to target elements this way, but of course that means that once the CSS is inlined, those attributes remain behind. Can they be removed somehow?

Premailed uses CsQuery, which is similar to jQuery. If it were jQuery I'd do a `*[class]` and `*[id]` and then `each(function() { ...` for them and then `(this).removeAttr("class")` and `(this).removeAttr("id")`. Maybe that's a start?

**Comment by martinnormark** [comment]
This can now be achieved by passing `true` to a new `stripIdAndClassAttributes`:

`PreMailer.MoveCssInline(input, false, stripIdAndClassAttributes: true)`

**Comment by denisz1** [comment]
@martinnormark works well on this side... thanks!
