### ISSUE TITLE
Premailer preserves !important in css rules.

### ISSUE THREAD

**Issue by AndersBillLinden** [milkshakesoftware/PreMailer.Net#57]
If I have this input:

``` html
<html>
  <head>
    <style type="text/css">
      .foo
      {
         width: 300px !important;
      }
    </style>
  </head>
  <body>
    <div class="foo" style="width: 200px"></div>
  </body>
</html>
```

premailer generates this output:

``` html
<html><head>

  </head>
  <body>
    <div class="foo" style="width: 300px !important"></div>

</body></html>
```

However, is there a way to instead have this html generated?

``` html
<html><head>

  </head>
  <body>
    <div class="foo" style="width: 300px"></div>

</body></html>
```

`!important` is not needed any longer in inline styles, is it?

**Comment by tobio** [comment]
@AndersBillLinden maintaining the ```!important``` flag in the final inline styles is required is some edge cases. Namely when the source ```style``` tags are left in the html document. Take a look at the following example, Premailer will correctly apply the inline styles, however leaving the source styles in the document will mean that Outlook (for example, really anything that doesn't support :first-child) will override the inline styling with the incorrect style. 

```html
<html>
<head>
<style type="text/css">
a { color: red !important }
a:first-child { color: blue !important }
</style>
</head>
<body>
<a href="http://example.com">This should be Blue</a>
<a href="http://example.com">This should be Red</a>
</body>
</html>
