### ISSUE TITLE
Media tags are removed?

### ISSUE THREAD

**Issue by AndersBillLinden** [milkshakesoftware/PreMailer.Net#59]
I am trying to use Premailer.NET to create responsive newsletters. However, `@media` tags seems to get stripped away. Where do they go?

**Comment by martinnormark** [comment]
Take a look at the [Media queries](https://github.com/milkshakesoftware/PreMailer.Net#media-queries) section of the readme.

You have to wrap your responsive styles in it's own `style` tag with an id, and add that id to the `ignoreElements` parameter you can pass to `MoveCssInline`.

Those styles won't be inlined, and the `style` tag will remain in the email for the device to resolve.

**Comment by AndersBillLinden** [comment]
I am using this for responsive newsletters. We are trying _ink_ and _zurb_ that are the developers of _ink_ made an inliner you maybe are familiar with on http://zurb.com/ink/inliner.php. It moves media queries inside the `<body>`. Keeping `<style>` tags inside `<body>` will for some reason work in old email clients. To me thats really hard to believe. I consider to use Premailer.NET. The second options is creating a web client that will interface that _zurb_ made form. Then I depend on the form to stay like it is and never change.

**Comment by martinnormark** [comment]
:+1:

**Comment by AndersBillLinden** [comment]
So you recommend me to use that zurb form?

**Comment by martinnormark** [comment]
Oh, I didn't realize it was a question.

If all you miss in PreMailer.Net is to keep the media queries, it is possible using the `ignoreElements` parameter to refer to style blocks that contain the media queries (and excludes all non-media wrapped styles).

That said, use what gives you the best result.

**Comment by AndersBillLinden** [comment]
I will test some stuff and see! Thanks

**Comment by chaoaretasty** [comment]
I've also been using Zurb Foundation for Email and came across this same issue. I've added a PR that enables PreMailer.Net to work with Zurb and CSS from other preprocessors.
