### ISSUE TITLE
Emojis converted to ?? like other online converters

### ISSUE THREAD

**Issue by MonsterMMORPG** [milkshakesoftware/PreMailer.Net#63]
This is extremely annoying

Example emoji 🎤 converted into ??

**Comment by martinnormark** [comment]
Can you post some before and after code?

**Comment by MonsterMMORPG** [comment]
actually my bad

they are converted i see 

like encoded but i dont know how to decode

i noticed it was my error of displaying ??

here before code

💎 You're receiving this newsletter because you've subscribed to our Newsletter when you registered to our game *|game_name|*. 🔬 However you can immediately unsubscribe from our newsletter with:

here after code

&#128142; You're receiving this newsletter because you've subscribed to our Newsletter when you registered to our game *|game_name|*. &#128300; However you can immediately unsubscribe from our newsletter with:

**Comment by MonsterMMORPG** [comment]
haha browser displayed them correctly let me check my issue :)

**Comment by MonsterMMORPG** [comment]
yep it works great in email even though they are encoded

this issue can be closed 

they are displayed like

```
💎 You're receiving this newsletter because you've subscribed to our Newsletter when you registered to our game *|game_name|*. 🔬 However you can immediately unsubscribe from our newsletter with:
```

```
 &#128142; You're receiving this newsletter because you've subscribed to our Newsletter when you registered to our game *|game_name|*. &#128300; However you can immediately unsubscribe from our newsletter with:
```

**Comment by martinnormark** [comment]
Alright, thanks. Closing it now.
