### ISSUE TITLE
References external CSS files

### ISSUE THREAD

**Issue by xatzz** [milkshakesoftware/PreMailer.Net#67]
This suggestion was reported originally by Rick Dorris on the comments section of your article (http://martinnormark.com/move-css-inline-premailer-net/) and I've searched through the issues list and didn't find nothing related to this.

So, is it possible to PreMailer process the references to external CSS files so we don't have to copy the (sometimes enormous) CSS styles to the HTML page?

Thanks

**Comment by martinnormark** [comment]
There's an optional `css` parameter you can specify when calling `MoveCssInline`.

That means you're responsible for downloading it, but you don't have to shove it into the DOM anymore.

**Comment by anitaisep** [comment]
Can you give me a example of how to use it, please?

**Comment by martinnormark** [comment]
```csharp
string htmlSource = File.ReadAllText(@"C:\Workspace\testmail.html");
string cssSource = File.ReadAllText(@"C:\Workspace\style.css");

var result = PreMailer.MoveCssInline(htmlSource, css: cssSource);
```

**Comment by Lion-HC** [comment]
Hello!
I noticed that in last update:
> PreMailer will download and use external style sheets as long as the value of href ends with .css.

It is great feature!
But unfortunately, ASP.NET (MVC) bundle ends with query, and not contains ".css" at all.

Can you extend CssLinkNodes method to return rel="stylesheet" also?

`return elements.Where(e => e.Attributes.Any(a => a.Name.Equals("href", StringComparison.OrdinalIgnoreCase) &&
						 (a.Value.EndsWith(".css", StringComparison.OrdinalIgnoreCase) || 
						 (e.Attributes.Any(r => r.Name.Equals("rel", StringComparison.OrdinalIgnoreCase) &&
												r.Value.Equals("stylesheet", StringComparison.OrdinalIgnoreCase))))));`

**Comment by martinnormark** [comment]
That should be possible, yes. Fancy a Pull Request with a unit test to prove the feature?

**Comment by DonDavio** [comment]
I'm facing the same issue and it looks like @Lion-HC's commit will solve it. Do you know if this change will be in 1.5.4?

**Comment by martinnormark** [comment]
It's in master so as soon as I cut a new release it will be included in the package.

**Comment by DonDavio** [comment]
Fantastic, thanks very much.

**Comment by martinnormark** [comment]
@DonDavio Your PR and fix for this issue was released yesterday, so grabbing bundles should work now.
