### ISSUE TITLE
PreMailer.net is unable to process the pseudo class/element due to limitation in CsQuery

### ISSUE THREAD

**Issue by akeilox** [milkshakesoftware/PreMailer.Net#69]
Hi there

I just downloaded the Premailer.NET today and build in VS2013, when I try to do a simple call like
string htmlSource = System.IO.File.ReadAllText(@"c:\sidebar-hero.html");
var result = PreMailer.MoveCssInline(htmlSource)

on a ZURB INK template sidebar-hero.html  (http://zurb.com/ink/downloads/templates/sidebar-hero.html )

I get the warning as following: 
PreMailer.Net is unable to process the pseudo class/element 'a:active' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'a:hover' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'a:visited' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'h1 a:active' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'h1 a:visited' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'h2 a:active' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'h2 a:visited' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'h3 a:active' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'h3 a:visited' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'h4 a:active' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'h4 a:visited' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'h5 a:active' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'h5 a:visited' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'h6 a:active' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'h6 a:visited' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.alert:hover td' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.button td a:visited' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.button:active td' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.button:active td a' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.button:hover td' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.button:hover td a' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.button:visited td' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.button:visited td a' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.facebook:hover td' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.google-plus:hover td' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.large-button td a:visited' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.large-button:active td a' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.large-button:hover td' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.large-button:hover td a' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.medium-button td a:visited' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.medium-button:active td a' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.medium-button:hover td' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.medium-button:hover td a' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.secondary td a:visited' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.secondary:active td a' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.secondary:hover td' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.secondary:hover td a' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.small-button td a:visited' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.small-button:active td a' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.small-button:hover td' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.small-button:hover td a' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.success:hover td' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.tiny-button td a:visited' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.tiny-button:active td a' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.tiny-button:hover td' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.tiny-button:hover td a' due to a limitation in CsQuery.

PreMailer.Net is unable to process the pseudo class/element 'table.twitter:hover td' due to a limitation in CsQuery.

**Comment by martinnormark** [comment]
This is a known limitation of CsQuery which is used under the hood. 

Look at the readme of premailer here on github under the notes section and pseudo links are mentioned.

**Comment by akeilox** [comment]
Hi Martin

I saw the note below. Is there any solution to this, patch/hack to make it work?

<pre>Pseudo classes/elements are not supported by CsQuery (which PreMailer.Net uses internally). Any that are encountered in your HTML will be ignored and logged to the InlineResult.Warnings collection</pre>

**Comment by martinnormark** [comment]
It's all in CsQuery - but for inlining they don't make much sense anyway.

You can't decide at the time of inlining that a button should have hover or active style. Because that's only relevant in the event of that happening.

But for email, you can leave these styles in the style block and just discard the warnings. Email clients that support these selectors knows how to use the non-inlined style block.

Then there's the `last-child` and similar pseudo classes that you can't use. To work around that you can add a regular CSS class to those elements.

**Comment by akeilox** [comment]
Thanks for the heads up. Understood hover and active style point, I saw this post below and wasnt sure if there was a code update that I was missing:
https://github.com/milkshakesoftware/PreMailer.Net/issues/34

Moving forward, ignoring the hover and active styles, to let the media queries stay/work as intented I moved all media queries under separate <style id="ignore" 
and call premailer with 
var result = PreMailer.MoveCssInline(htmlSource, false, ignoreElements: "#ignore");

but in the example of ZURB INK framework sample, it seems to break the media query view;
Sample i used is from their boiler plate sample;
http://zurb.com/ink/downloads/templates/sidebar-hero.html 

when i run the same html on the cssinliner.com it seems to work fine. 

Not sure if im missing any step in between.

**Comment by martinnormark** [comment]
It seems most pseudo classes is supported, except for these: https://github.com/milkshakesoftware/PreMailer.Net/blob/master/PreMailer.Net/PreMailer.Net/CssSelectorParser.cs#L164

Ignoring media queries should work with what you outlined. I don't know if there's any specific issues with the ZURB INK framework.

**Comment by akeilox** [comment]
Hi again

I really want the PreMailer.NET to work with the INK email framework, as its a very popular and bootstrap-like approach.

I checked the pseudo classed in the referenced CssSelectorParser.cs#L164 and went ahead and moved all pseudo and media queries to a separate < style id="ignore >

The example (boiler plate) from INK used is http://zurb.com/ink/downloads/templates/sidebar-hero.html

The following is the re-arranged CSS, with pseudo and media queries moved under separate style with id ignore: http://paste.ofcode.org/bHtdxjAhXPri882Ta77hBs

If I run the premailer, 0 (zero) warnings show. A big relief!......

But then for some mysterious reason, the second column colapsing below 600pixel is not working but all the other responsiveness works - just not that collapsing of the sidebar.

I think its almost there but I cant figure out what is causing it.

If you can get a quick look, with above linked INK's boiler plate code and re-arranged CSS above
can you spot what is likely to be causing the issue?

For clarification I run the Premailer code like;
string htmlSource = System.IO.File.ReadAllText(@"N:\INK\sidebar-hero.html");
var result = PreMailer.MoveCssInline(htmlSource, false, ignoreElements: "#ignore");

I feel there is something obvious, that I am not seeing..but cant figure it out.

**Comment by martinnormark** [comment]
I'm sorry, but I really can't look into that. Sorry :raised_hands:

**Comment by akeilox** [comment]
Thanks for the swift reply Martin. Understand. I hope someone stumbling across this post with similar issue can shed some light on the mystery.
