### ISSUE TITLE
 Unexpected character found at position 20: ".. l > input::>>-<<moz-placeholder"

### ISSUE THREAD

**Issue by k2evil** [milkshakesoftware/PreMailer.Net#79]
Hi
I tried to in lining a webpage css... I passed url to constructor and when I called MoveCssInline, System.ArgumentException thrown by CsQuery...
How can I fix it?

**Comment by k2evil** [comment]
Please answer me!!

**Comment by martinnormark** [comment]
Can you post the CSS you tried inlining?

**Comment by smkanadl** [comment]
I think I had a similar issure when using the [::-ms-clear](https://developer.mozilla.org/en-US/docs/Web/CSS/::-ms-clear) pseudo-element.

`input[type=text]::-ms-clear {
    color:red;
}`

**Comment by martinnormark** [comment]
This is fixed by AngleSharp introduced in #76 - so when I cut a new release to Nu Get, you can get this fixed.
