### ISSUE TITLE
add support for inlining css specified as <link> elements

### ISSUE THREAD

**Issue by jamesmanning** [milkshakesoftware/PreMailer.Net#8]
Not sure if it'll be possible to 'convert' link elements into style elements (fetch content, then replace) and then go through the existing code path or not.

**Comment by edikep2000** [comment]
Please has this issue been fixed? I am kind of in a fix with this issue and will really appreciate some light on this

**Comment by martinnormark** [comment]
Since the fix of #45 done in e375b9f7a32d1ded3dcd4e9f67f9b942e5bff6db you can specify a CSS string as a parameter when calling PreMailer:

`PreMailer.MoveCssInline(input, false, css: ".test { background-color:#f1f1f1; }")`

Part of the [options](https://github.com/milkshakesoftware/PreMailer.Net#options).

**Comment by edikep2000** [comment]
I know about that, I am wondering if it is possible to do stuff like this

PreMailer.MoveCssInline(input, false, css: "~/pathToCss")

and If it is possible to pass in more than one CSS file if the aforementioned exists

**Comment by martinnormark** [comment]
It isn't. But it should be straight forward to load the files yourself into a string and pass that to PM.

**Comment by edikep2000** [comment]
Unfortunately, I cant find any information as to how this can be achieved. Any Pointers please

**Comment by martinnormark** [comment]
Check out the last comment in issue #67

**Comment by martinnormark** [comment]
Downloading external CSS files (specified as `link href="..."` elements are now possible, thanks to #67 merged in #109 and pushed to [Nu Get as v1.5.4](https://www.nuget.org/packages/PreMailer.Net/1.5.4) yesterday.
