### ISSUE TITLE
Why does premailer add <tbody> tags

### ISSUE THREAD

**Issue by darrenshrwd** [milkshakesoftware/PreMailer.Net#80]
Why does premailer add **tbody** tags?

Perhaps more of a question, but searching a bit suggests it's not required.

**Comment by martinnormark** [comment]
It's done by CsQuery, perhaps it changes since swithing to AngleSharp in #76. Will check.

**Comment by martinnormark** [comment]
I checked with AngleSharp, and it will inject `tbody` tags if they're not there.
