### ISSUE TITLE
Add support for pseudo-classes

### ISSUE THREAD

**Issue by CodeAnimal** [milkshakesoftware/PreMailer.Net#82]
This could be done by collecting all the pseudo-class styles found and then appending a new style element with all the pseudo-classes that cannot be placed inline to the end of the head tag.

I guess this would only be necessary if the `RemoveStyleElements` parameter is True.

**Comment by martinnormark** [comment]
I have to test the pseudo classes after the change to AngleSharp in #76 - it should work, as far as I can tell by looking into the capabilities of AngleSharp.

**Comment by CodeAnimal** [comment]
Sorry, I didn't make myself very clear. I mean for styles like `:hover`, `:active` and `:visited` which cannot be preprocessed.

**Comment by martinnormark** [comment]
Yeah, ok. That would be a good thing to do. Looking into AngleSharp now, and at least it doesn't throw an exception when faced with an unsupported selector.

But I still think I'll keep the concept of unsupported selectors, since some does not make sense to preprocess - as you outlined above.
