### ISSUE TITLE
Css Standardization

### ISSUE THREAD

**Issue by k2evil** [milkshakesoftware/PreMailer.Net#83]
Hi again and sorry for I had to ask again my question because i can't wait until new version but this time I come with more details.
Ok... I used a little trick... I downloaded the css file of page and saved it in a string variable:
```
             foreach (HtmlElement he in webBrowser.Document.GetElementsByTagName("link"))
                {
                    if (he.GetAttribute("rel").Equals("stylesheet"))
                    {
                        css = "http://www.varzesh3.com" + he.GetAttribute("href");
                        break;
                    }
                }
                dler = new HttpDownloader(css, null, null);
                css = dler.GetPage();
```
(HttpDownloader is a class that i wrote it myself)

Then I deleted css links in html file and pass `css` as my Css file.
```
                foreach (HtmlElement he in webBrowser.Document.GetElementsByTagName("link"))
                {
                    if (he.GetAttribute("rel").Equals("stylesheet"))
                    {
                        htmlSource = htmlSource.Replace(he.OuterHtml, "");
                    }
                }
```
Then I removed all rules in css that has one or more ":" character in their names.
```
string undefinedRuleRegex = @"(^.+:{1,2}[^\{\}]+\{(\n|[^\{\}])+\})";
                for (Match results = Regex.Match(css, undefinedRuleRegex, RegexOptions.Multiline); results.Success; results = Regex.Match(css, undefinedRuleRegex,RegexOptions.Multiline))
                {
                    css = css.Replace(results.Groups[0].ToString(),"");
                }
var pm = new PreMailer.Net.PreMailer(htmlSource, new Uri("http://www.varzesh3.com"));
                
                var result = pm.MoveCssInline(false,null, css);
```
but again i get that exeption again! This is the links of "css" files of webpage:
 ```
<!--Application CSS Files-->
    <link rel="stylesheet" type="text/css" href="/OStatic/css/main.css?version=73" />
    <!--[if IE 8]>
    <link rel="stylesheet" type="text/css" href="/OStatic/css/main-ie.css?version=1" />
    <![endif]-->
    
    <link rel="stylesheet" type="text/css" href="/OStatic/css/comment.css" />

```

And this is the exeption information:
```
An exception of type 'System.ArgumentException' occurred in CsQuery.dll but was not handled in user code

Additional information: Unexpected character found at position 20: ".. l > input::>>-<<moz-placeholder"
```
Can u please give me some advise that fix this problem?

**Comment by k2evil** [comment]
I changed the code and its worked correct
for removing stylesheet link, used Regex:
```
string cssLinkRegex = @"(^\s*<\s*link\s*rel\s*=\s*""stylesheet""[^>]*>)";
                for (Match results = Regex.Match(htmlSource, cssLinkRegex, RegexOptions.Multiline); results.Success; results = Regex.Match(htmlSource, cssLinkRegex, RegexOptions.Multiline))
                {
                    htmlSource = htmlSource.Replace(results.Groups[0].ToString(), "");
                }
```
And pass `css` and `htmlSource` to your code.
```
var pm = new PreMailer.Net.PreMailer(htmlSource);
                
                var result = pm.MoveCssInline(false,null, css);
```
But I have Encoding Issue... Webpage contains Persian characters (UTF8 characters). but in output characters didn't show correctly... for example:
`<title>گلزنی دژاگه در شب حضور ایرانی‌ها :: ورزش 3 </title>`
shown as:
`<title>&#1711;&#1604;&#1586;&#1606;&#1740; &#1583;&#1688;&#1575;&#1711;&#1607; &#1583;&#1585; &#1588;&#1576; &#1581;&#1590;&#1608;&#1585; &#1575;&#1740;&#1585;&#1575;&#1606;&#1740;&#8204;&#1607;&#1575; :: &#1608;&#1585;&#1586;&#1588; 3 </title>`

**Comment by martinnormark** [comment]
The output is HTML encoded. Should display fine when rendered.

I used Chrome DevTools to add the encoded HTML to an element in this page:
![image](https://cloud.githubusercontent.com/assets/67565/12670871/1d11a4cc-c66c-11e5-9263-8f28ffc13009.png)

If I copy-paste the string you wrote, and the rendered output on this page the following expression evaluates as `true`:
`"گلزنی دژاگه در شب حضور ایرانی‌ها :: ورزش 3" == "گلزنی دژاگه در شب حضور ایرانی‌ها :: ورزش 3"`
