### ISSUE TITLE
Character limit on premailer

### ISSUE THREAD

**Issue by Asha-D** [milkshakesoftware/PreMailer.Net#88]
We noticed when premailing our markup for emails that there is a character limit of 2^15 (32768 characters) We wondered if this was a deliberate design choice as it's concatenating our email significantly (strangely removing content from the middle of the email rather than the end). We've gotten around the problem by stripping all white space but there is still the potential for issues.

Looks like maybe a short (Int16) is used somewhere and that's the limiting factor?

**Comment by martinnormark** [comment]
This is not a design choice!

I have a hunch of CsQuery being the culprit - in the current version PreMailer uses CsQuery - but a new release is actually ready to go, which uses AngleSharp as the DOM library which generates the resulting HTML.

Do you have the opportunity to grab the current master branch (not using Nu Get) and test your email with that? Could be an interesting test of AngleSharp.

**Comment by Asha-D** [comment]
I'll give it a try when I get into my office today. I had downloaded the master with the intention of reviewing the code. Thanks I'll let you know the outcome.

**Comment by Asha-D** [comment]
No dice I'm afraid. We've had the exact same outcome with the new version. A lot of styles are being added to each <td> it's a legacy system that has some badly written markup so that's not helping with bloated email content but it's still strange.

**Comment by itlackey** [comment]
It seems I am having a similar issue. Any suggestions / or work around anyone has come up with?

**Comment by martinnormark** [comment]
Can anyone post some code to reproduce this? I'm currently testing with content of more than 100k characters, and it doesn't seem to cut anything off.

**Comment by Asha-D** [comment]
I'm currently working on something else but I'll try and post something up tomorrow with the code I'm using.

**Comment by ketchol** [comment]
I've tried with content of more than 130k characters. And it's failing. Are there any work around methods for this?

**Comment by martinnormark** [comment]
Can you share the HTML you used (as a ZIP here), and confirm it was tested with the latest version of PreMailer?

As mentioned earlier, I couldn't get it failing with 100k chars.

**Comment by ketchol** [comment]
Hi martinnormark, thanks for your prompt reply. Please check the attached zip file for HTML code.
[premailer_test.zip](https://github.com/milkshakesoftware/PreMailer.Net/files/241573/premailer_test.zip)

**Comment by MSCAU** [comment]
Hi Martin, this is also of interest to me. Any movement on this issue?

**Comment by Asha-D** [comment]
Seems our problem was with visual studio. The variable preview window only shows 32768 characters so we thought the text was being truncated. Our development environment isn't configured to send emails so we falsely thought the email markup was being truncated. It wasn't.

**Comment by martinnormark** [comment]
Alright, thanks for the update!
