### ISSUE TITLE
Return Underlying Document

### ISSUE THREAD

**Issue by neurospeech** [milkshakesoftware/PreMailer.Net#89]
It would be nice to have access to underlying Document, this would allow us to do some extra processing, such as changing links to tracking links etc, without reparsing document again.

Or simply make private fields protected, we can add some extra processing.

**Comment by martinnormark** [comment]
I know this is more flexible, and you're probably adding more that just query params to links - but are you aware of the [`AddAnalyticsTags`](https://github.com/milkshakesoftware/PreMailer.Net/blob/master/PreMailer.Net/PreMailer.Net/PreMailer.cs#L135-L148) method introduced in #61?

**Comment by neurospeech** [comment]
No, I have lot of other things to do, for example 

1. Change image/css urls to CDN only if they match certain path
2. Add an 1x1 blank image at bottom for open tracking
3. Link tracking 

Now we have a mobile app, where we display same message which was sent to recipient in email, in this case (while user is in our mobile app), we have different links and we omit certain parts like logo and footer etc.

**Comment by martinnormark** [comment]
Alright, cool :neckbeard:
