### ISSUE TITLE
add support for composed fonts using quotes like "New Times Roman"

### ISSUE THREAD

**Issue by RomiPierre** [milkshakesoftware/PreMailer.Net#9]
Composed fonts like "New Times Roman" and others fonts using quotes in style sheets are generating an error during parsing styles.

Sample
<p style="font-family: georgia, " times="" new="" roman",="" times,="" serif!important;line-height:="" 1.3em;padding-left:="" 0px;padding-right:="" 15px;padding-top:="" 3px;text-align:="" justify!important;"="">

**Comment by martinnormark** [comment]
I tested this since the introduction of AngleSharp in #76, and it now works.

The markup and CSS above produces the following when inlined, which is valid: http://stackoverflow.com/a/5352973/2972

```html
<div style=\"font-family: &quot;New Times Roman&quot;\"></div>
```
