### ISSUE TITLE
Targeting to Framework 4.0

### ISSUE THREAD

**Issue by agarciacalvo** [milkshakesoftware/PreMailer.Net#95]
Starting from version 1.5.0 it's required the 4.5 framework. However, AngleSharp seems that works with the 4.0 framework. It would be possible to target the 4.0 framework to win greater support for multiple projects or is there  another reason to have made the change? Thank you in advance.

**Comment by tommytayman** [comment]
There are too many goodies in .NET 4.5/4.6 over 4.0 for many package authors to stick to 4.0.  As well, .NET 4.0 is now over 6 years old.

**Comment by martinnormark** [comment]
Targeting now is .NET 4.0, once the .NET Core branch gets done it will target multiple frameworks.

**Comment by martinnormark** [comment]
Sorry, I read f347c3a18649732cd177d26131f29e144dd17fed and thought it was targeting of the whole project. Still on 4.5, won't do more until .NET Core is running to target multiple frameworks.

**Comment by agarciacalvo** [comment]
I have sucessfully downloaded and compiled Premailer.NET to Framework 4 and there are no dependencies on the Framework 4.5.

AngleSharp suppors .NETStandard 1.0, .NETPortable, .NET 4.0, .NET 4.5 and Silverlight 5.0. I was asking for the same supporting schema. Anyway I've solved it with my own compilation. 

Best regards
