### ISSUE TITLE
Support for CoreCLR

### ISSUE THREAD

**Issue by TobbenTM** [milkshakesoftware/PreMailer.Net#96]
With the latest release of AngleSharp, they now support the CoreCLR runtime (https://github.com/AngleSharp/AngleSharp/issues/271), would it be possible for premailer to also include the target runtime?

Thanks

**Comment by NickolasAcosta** [comment]
@TobbenTM 

Would you be interested in trying out my fork for coreclr rc1 compatibility?  I compiled this against dnx451 and dnxcore50.

https://github.com/NickolasAcosta/PreMailer.Net/tree/coreclr-rc1

I need this for a personal project of mine, so I took some initiative.  I'll get back to you with my results tommorow.  All tests pass but do not run for dnxcore50 as moq is no longer compatible.

**Comment by TobbenTM** [comment]
@NickolasAcosta 

Sorry for the late response, finally got around to downloading and testing your build, works great! Have not run into any problems at all. Lets hope to get your functionality merged upstream

**Comment by martinnormark** [comment]
@NickolasAcosta If all unit tests are passing, please create a Pull Requests and we can hopefully merge!

**Comment by NickolasAcosta** [comment]
@TobbenTM Glad it's working out for you!

@martinnormark 
Unit tests do not execute on  the "dnxcore50" runtime.  This is because moq is not available for coreclr.
Unit tests do execute and pass on the "dnx451" runtime.

Moq is currently waiting on castlecore to update to rc2.
https://github.com/moq/moq4/issues/168

Would you like to wait for rc2?

**Comment by martinnormark** [comment]
@NickolasAcosta I've created a [`dotnet-core`](https://github.com/milkshakesoftware/PreMailer.Net/tree/dotnet-core) branch. If you make a PR against that, I'll merge and publish a pre-release package on Nu Get.

**Comment by NickolasAcosta** [comment]
@TobbenTM Have you made the jump to RC2 yet?

**Comment by TobbenTM** [comment]
@NickolasAcosta I have not, and probably won't have the time to migrate until after the summer unfortunately.

**Comment by TobbenTM** [comment]
@NickolasAcosta I have successfully migrated my project to RC2, and your port of PreMailer.Net still works for all of my use-cases. 

Furthermore, moq is now available and working great for .Net Core (RC2), though I have not run the tests for PreMailer.Net yet.

**Comment by NickolasAcosta** [comment]
Glad to hear it @TobbenTM .  RTM is in a few days, so I will probably take a look at the new Moq this week.

**Comment by freykeld** [comment]
Any ETA on a version with CoreCLR 1.0.0 RTM support?

**Comment by NickolasAcosta** [comment]
I will attempt to upgrade that branch today after work.  It will give me an excuse to play with the new moq.

**Comment by NickolasAcosta** [comment]
Current alpha version of Moq is not compatible with .net core rtm yet.  Hang tight!

https://github.com/moq/moq4/issues/168

**Comment by freykeld** [comment]
@NickolasAcosta 
Thanks for the update, i will keep a close on this issue.

**Comment by NickolasAcosta** [comment]
Try my fork.  No unit tests, but there are no compiler errors either :)

Use at your own risk obviously.
https://github.com/NickolasAcosta/PreMailer.Net/tree/dotnet-core

Many libraries are in are still in RC2 and working on RTM support.  Hopefully it all settles soon!

**Comment by freykeld** [comment]
@NickolasAcosta 
Worls fine for now, thanks.
My project is in a early alphastate so this will do fine for atlest a few months :+1:

**Comment by freykeld** [comment]
Any news on this issue? I have to deploy first version of my site soon.

**Comment by martinnormark** [comment]
The PR is here: #118, still a few things to iron out.

**Comment by superlogical** [comment]
@martinnormark Good shit, I'm just upgrading a project to .net core and this made my day!

**Comment by exiled78** [comment]
@superlogical  - would you mind explaining how you included this in your .net core project? I am also migrating and am a bit new to this. I downloaded this branch and added it as a project to the solution, then added "PreMailer.Net": "1.6.0-*", to the dependencies in project.json in my startup project (Web Api). 

Is this the best/only way? 

I would rather not have the Premailer project sitting in my solution and would rather just use it as a nuget package, but unless I am mistaken, only v1.5.5 is available on nuget which fails when added.

Thanks!

**Comment by xavierpena** [comment]
I tried @exiled78 solution and I got the following error:

    Package PreMailer.Net 2.0.0-alpha is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package PreMailer.Net 2.0.0-alpha supports: net45 (.NETFramework,Version=v4.5)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

**Comment by exiled78** [comment]
@xavierpena yes, that is what I ended up doing also.

**Comment by sebok** [comment]
For future reference, you can also directly download Nuget packages from [this release](https://github.com/sebok/PreMailer.Net/releases/tag/v1.5.6), which adds support for .NET Core on master branch in a very simple way. Corresponding pull request is #122.

**Comment by alexzaytsev-newsroomly** [comment]
Any news here? as .net core 2.0.0 is available and nuget says there is a .Net Framework 4.5 dependency in AngleSharp.

**Comment by martinnormark** [comment]
The latest pre-release version should work: https://www.nuget.org/packages/PreMailer.Net/2.0.0-beta2

**Comment by reinaldocoelho** [comment]
This is still an open issue?
Whe have It working on NetStandard?

**Comment by martinnormark** [comment]
Works on NETStandard now.
