### ISSUE TITLE
Doctype is removed by default

### ISSUE THREAD

**Issue by Romanx** [milkshakesoftware/PreMailer.Net#97]
Hey there,

Just a question if you mean to remove the doctype tag from the passed html as it was unexpected functionality. It seems to be related in that you get return the document element's OuterHtml to return [here.](https://github.com/milkshakesoftware/PreMailer.Net/blob/master/PreMailer.Net/PreMailer.Net/PreMailer.cs#L122)

If this is intentional then it's cool, if not then maybe a flag to determine if it should be removed or just return the whole document with the changes rather than just the html?

**Comment by martinnormark** [comment]
Hey @Romanx - this issue is resolved by changes in d416080f136bf2965971d63c5b5663070222e6c2.

Cutting a new release shortly.

**Comment by Romanx** [comment]
@martinnormark Thanks for the quick resolution!
