### ISSUE TITLE
Add manual resolution of external style sheets

### ISSUE THREAD

**Issue by coldacid** [milkshakesoftware/PreMailer.Net#98]
If my CSS is stored as an embedded resource, or within a zip file, or in an application's database, the external style sheet resolution automatically performed by PreMailer.Net is no good for me. It would be very helpful to have an event or provide a function callback that allows me to manually resolve an external style sheet and pass the CSS back to PreMailer.Net through it.

**Comment by martinnormark** [comment]
This is something that can be achieved already using the `css` parameter on the `MoveCssInline` method.

**Comment by coldacid** [comment]
Does that also add the CSS as content of a `<script>` tag to the HTML though?

**Comment by martinnormark** [comment]
Hey @coldacid - it does not add the CSS as content to the HTML.

PreMailer only provides basic functionality for gathering the CSS - since that is extremely application specific, I'd rather let it be up to the application developer to handle edge cases than try to bake in every possible option.
